<?php

namespace components\web;

class ResponseCodes
{
    public const CODE_CONTINUE = 100;
    public const CODE_SWITCHING_PROTOCOLS = 101;
    public const CODE_PROCESSING = 102;
    public const CODE_OK = 200;
    public const CODE_CREATED = 201;
    public const CODE_ACCEPTED = 202;
    public const CODE_NON_AUTHORITATIVE_INFORMATION = 203;
    public const CODE_NO_CONTENT = 204;
    public const CODE_RESET_CONTENT = 205;
    public const CODE_PARTIAL_CONTENT = 206;
    public const CODE_MULTI_STATUS = 207;
    public const CODE_ALREADY_REPORTED = 208;
    public const CODE_IM_USED = 226;
    public const CODE_MULTIPLE_CHOICES = 300;
    public const CODE_MOVED_PERMANENTLY = 301;
    public const CODE_FOUND = 302;
    public const CODE_SEE_OTHER = 303;
    public const CODE_NOT_MODIFIED = 304;
    public const CODE_USE_PROXY = 305;
    public const CODE_UNUSED = 306;
    public const CODE_TEMPORARY_REDIRECT = 307;
    public const CODE_PERMANENT_REDIRECT = 308;
    public const CODE_BAD_REQUEST = 400;
    public const CODE_UNAUTHORIZED = 401;
    public const CODE_PAYMENT_REQUIRED = 402;
    public const CODE_FORBIDDEN = 403;
    public const CODE_NOT_FOUND = 404;
    public const CODE_METHOD_NOT_ALLOWED = 405;
    public const CODE_NOT_ACCEPTABLE = 406;
    public const CODE_PROXY_AUTHENTICATION_REQUIRED = 407;
    public const CODE_REQUEST_TIMEOUT = 408;
    public const CODE_CONFLICT = 409;
    public const CODE_GONE = 410;
    public const CODE_LENGTH_REQUIRED = 411;
    public const CODE_PRECONDITION_FAILED = 412;
    public const CODE_REQUEST_ENTITY_TOO_LARGE = 413;
    public const CODE_REQUEST_URI_TOO_LONG = 414;
    public const CODE_UNSUPPORTED_MEDIA_TYPE = 415;
    public const CODE_REQUESTED_RANGE_NOT_SATISFIABLE = 416;
    public const CODE_EXPECTATION_FAILED = 417;
    public const CODE_IAM_TEAPOT = 418;
    public const CODE_ENHANCE_YOUR_CALM = 420;
    public const CODE_UNPROCESSABLE_ENTITY = 422;
    public const CODE_LOCKED = 423;
    public const CODE_FAILED_DEPENDENCY = 424;
    public const CODE_RESERVED_FOR_WEBDAV = 425;
    public const CODE_UPGRADE_REQUIRED = 426;
    public const CODE_PRECONDITION_REQUIRED = 428;
    public const CODE_TOO_MANY_REQUESTS = 429;
    public const CODE_REQUEST_HEADER_FIELDS_TOO_LARGE = 431;
    public const CODE_NO_RESPONSE = 444;
    public const CODE_RETRY_WITH = 449;
    public const CODE_BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS = 450;
    public const CODE_CLIENT_CLOSED_REQUEST = 499;
    public const CODE_INTERNAL_SERVER_ERROR = 500;
    public const CODE_NOT_IMPLEMENTED = 501;
    public const CODE_BAD_GATEWAY = 502;
    public const CODE_SERVICE_UNAVAILABLE = 503;
    public const CODE_GATEWAY_TIMEOUT = 504;
    public const CODE_HTTP_VERSION_NOT_SUPPORTED = 505;
    public const CODE_VARIANT_ALSO_NEGOTIATES = 506;
    public const CODE_INSUFFICIENT_STORAGE = 507;
    public const CODE_LOOP_DETECTED = 508;
    public const CODE_BANDWIDTH_LIMIT_EXCEEDED = 509;
    public const CODE_NOT_EXTENDED = 510;
    public const CODE_NETWORK_AUTHENTICATION_REQUIRED = 511;
    public const CODE_NETWORK_READ_TIMEOUT_ERROR = 598;
    public const CODE_NETWORK_CONNECT_TIMEOUT_ERROR = 599;

    private static array $messages = [
        self::CODE_CONTINUE => 'Continue',
        self::CODE_SWITCHING_PROTOCOLS => 'Switching Protocols',
        self::CODE_PROCESSING => 'Processing (WebDAV)',
        self::CODE_OK => 'OK',
        self::CODE_CREATED => 'Created',
        self::CODE_ACCEPTED => 'Accepted',
        self::CODE_NON_AUTHORITATIVE_INFORMATION => 'Non-Authoritative Information',
        self::CODE_NO_CONTENT => 'No Content',
        self::CODE_RESET_CONTENT => 'Reset Content',
        self::CODE_PARTIAL_CONTENT => 'Partial Content',
        self::CODE_MULTI_STATUS => 'Multi-Status (WebDAV)',
        self::CODE_ALREADY_REPORTED => 'Already Reported (WebDAV)',
        self::CODE_IM_USED => 'IM Used',
        self::CODE_MULTIPLE_CHOICES => 'Multiple Choices',
        self::CODE_MOVED_PERMANENTLY => 'Moved Permanently',
        self::CODE_FOUND => 'Found',
        self::CODE_SEE_OTHER => 'See Other',
        self::CODE_NOT_MODIFIED => 'Not Modified',
        self::CODE_USE_PROXY => 'Use Proxy',
        self::CODE_UNUSED => '(Unused)',
        self::CODE_TEMPORARY_REDIRECT => 'Temporary Redirect',
        self::CODE_PERMANENT_REDIRECT => 'Permanent Redirect (Experimental)',
        self::CODE_BAD_REQUEST => 'Bad Request',
        self::CODE_UNAUTHORIZED => 'Unauthorized',
        self::CODE_PAYMENT_REQUIRED => 'Payment Required',
        self::CODE_FORBIDDEN => 'Forbidden',
        self::CODE_NOT_FOUND => 'Not Found',
        self::CODE_METHOD_NOT_ALLOWED => 'Method Not Allowed',
        self::CODE_NOT_ACCEPTABLE => 'Not Acceptable',
        self::CODE_PROXY_AUTHENTICATION_REQUIRED => 'Proxy Authentication Required',
        self::CODE_REQUEST_TIMEOUT => 'Request Timeout',
        self::CODE_CONFLICT => 'Conflict',
        self::CODE_GONE => 'Gone',
        self::CODE_LENGTH_REQUIRED => 'Length Required',
        self::CODE_PRECONDITION_FAILED => 'Precondition Failed',
        self::CODE_REQUEST_ENTITY_TOO_LARGE => 'Request Entity Too Large',
        self::CODE_REQUEST_URI_TOO_LONG => 'Request-URI Too Long',
        self::CODE_UNSUPPORTED_MEDIA_TYPE => 'Unsupported Media Type',
        self::CODE_REQUESTED_RANGE_NOT_SATISFIABLE => 'Requested Range Not Satisfiable',
        self::CODE_EXPECTATION_FAILED => 'Expectaion Failed',
        self::CODE_IAM_TEAPOT => 'I\'m a teapot (RFC 2324)',
        self::CODE_ENHANCE_YOUR_CALM => 'Enhance Your Calm (Twitter)',
        self::CODE_UNPROCESSABLE_ENTITY => 'Unprocessable Entity (WebDAV)',
        self::CODE_LOCKED => 'Locked (WebDAV)',
        self::CODE_FAILED_DEPENDENCY => 'Failed Dependency (WebDAV)',
        self::CODE_RESERVED_FOR_WEBDAV => 'Reserved For WebDAV',
        self::CODE_UPGRADE_REQUIRED => 'Upgrade Requred',
        self::CODE_PRECONDITION_REQUIRED => 'Precondition Required',
        self::CODE_TOO_MANY_REQUESTS => 'Too Many Requests',
        self::CODE_REQUEST_HEADER_FIELDS_TOO_LARGE => 'Request Header Fields Too Large',
        self::CODE_NO_RESPONSE => 'No Response (Nginx)',
        self::CODE_RETRY_WITH => 'Retry With (Microsoft)',
        self::CODE_BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS => 'Blocked by Windows Parental Controls (Microsoft)',
        self::CODE_CLIENT_CLOSED_REQUEST => 'Client Closed Request (Nginx)',
        self::CODE_INTERNAL_SERVER_ERROR => 'Internal Server Error',
        self::CODE_NOT_IMPLEMENTED => 'Not Implemented',
        self::CODE_BAD_GATEWAY => 'Bad Gateway',
        self::CODE_SERVICE_UNAVAILABLE => 'Service Unavailable',
        self::CODE_GATEWAY_TIMEOUT => 'Gateway timeout',
        self::CODE_HTTP_VERSION_NOT_SUPPORTED => 'HTTP Version Not Supported',
        self::CODE_VARIANT_ALSO_NEGOTIATES => 'Variant Also Negotiates (Experimental)',
        self::CODE_INSUFFICIENT_STORAGE => 'Insufficient Storage (WebDAV)',
        self::CODE_LOOP_DETECTED => 'Loop Detected (WebDAV)',
        self::CODE_BANDWIDTH_LIMIT_EXCEEDED => 'Bandwidth Limit Exceeded (Apache)',
        self::CODE_NOT_EXTENDED => 'Not Extended',
        self::CODE_NETWORK_AUTHENTICATION_REQUIRED => 'Network Authentication Required',
        self::CODE_NETWORK_READ_TIMEOUT_ERROR => 'Network Read Timeout Error',
        self::CODE_NETWORK_CONNECT_TIMEOUT_ERROR => 'Connect Timeout Error',
    ];

    public static function getMessageByCode($code): string
    {
        return self::$messages[$code] ?? '';
    }
}
